### ISSUE TITLE
AVcc not working on Arduino Mega

### ISSUE THREAD

**Issue by caortiz97** [JChristensen/CurrentTransformer#1]
Started having issues when running the library on my Arduino Mega, it didn't work as well as in the Arduino Uno. After some testing I discovered that the variable m_vcc of CT_Control was different. I think that the method used for calculating the analog voltage is not very robust. Maybe you should check this guide https://provideyourown.com/2012/secret-arduino-voltmeter-measure-battery-voltage/. I used this method instead and everything worked on both kinds of Arduino

Thank you for your work

**Comment by JChristensen** [comment]
@caortiz97, the library should now (v2.3.0) support ATmega2560 and ATmega1280 in addition to ATmega328/P. I do not have either a 2560 or 1280 to test with. If you could give it a try and let me know how it works, I'd appreciate it.

Thanks ... Jack

PS: 2.3.0 is available via the Arduino Library Manager.
